PRAGMA foreign_keys = ON;
PRAGMA foreign_keys;

CREATE TABLE IF NOT EXISTS usuarios(
    ID PRIMARY KEY AUTOINCREMENT,
    nome TEXT(100) NOTNULL,
    login TEXT(50) NOTNULL DISTINCT,
    senha TEXT(20) NOTNULL
);

CREATE TABLE IF NOT EXISTS fabricante(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT(80) NOTNULL
);

CREATE TABLE IF NOT EXISTS imp_models(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT(50) NOTNULL,
    Description TEXT(150),
    f_fabricante INTEGER  NOTNULL,
    FOREIGN KEY (f_fabricante) REFERENCES fabricante(ID)
);

CREATE TABLE IF NOT EXISTS impressoras(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Cod INTEGER NOTNULL DISTINCT,
    Local TEXT(100) NOTNULL,
    Status TEXT(50) NOTNULL,
    n_serie TEXT(100) NOTNULL
);

CREATE TABLE IF NOT EXISTS cart_estado(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    situacao TEXT(100) NOTNULL
);

CREATE TABLE IF NOT EXISTS cart_model(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT(100) NOTNULL,
    f_imp_model INTEGER NOTNULL,
    FOREIGN KEY (f_imp_model) REFERENCES imp_models(ID)
);

CREATE TABLE IF NOT EXISTS cart_data_entrada(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    data TEXT(30) NOTNULL,
    f_usuario INTEGER NOTNULL,
    FOREIGN KEY (f_usuario) REFERENCES usuarios(ID)
);

CREATE TABLE IF NOT EXISTS cart_data_saida(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    data TEXT(30) NOTNULL,
    f_usuario INTEGER NOTNULL,
    FOREIGN KEY (f_usuario) REFERENCES usuarios(ID)
);

CREATE TABLE IF NOT EXISTS cart_data_instalacao(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    data TEXT(30) NOTNULL,
    f_usuario INTEGER NOTNULL,
    FOREIGN KEY (f_usuario) REFERENCES usuarios(ID)
);
